config/routes.rb
Federails::Engine.routes.draw do
  if Federails.configuration.enable_discovery
    scope path: '/' do
      get '/.well-known/webfinger', to: 'server/web_finger#find', as: :webfinger
      get '/.well-known/host-meta', to: 'server/web_finger#host_meta', as: :host_meta
      get '/.well-known/nodeinfo', to: 'server/nodeinfo#index', as: :node_info
      get '/nodeinfo/2.0', to: 'server/nodeinfo#show', as: :show_node_info
    end
  end

  scope Federails.configuration.client_routes_path, module: :client, as: :client do
    resources :activities, only: [:index, :feed]
    resources :actors, only: [:index, :show] do
      collection do
        get :lookup, to: 'actors#lookup'
      end
      resources :activities, only: [:index]
    end
    get :feed, to: 'activities#feed'
    resources :followings, only: [:create, :destroy] do
      collection do
        post :follow, to: 'followings#follow'
      end

      member do
        put :accept, to: 'followings#accept'
      end
    end
  end

  scope Federails.configuration.server_routes_path, module: :server, as: :server do
    resources :actors, only: [:show] do
      member do
        get :followers
        get :following
      end
      get :outbox, to: 'activities#outbox'
      post :inbox, to: 'activities#create'
      resources :activities, only: [:show]
      resources :followings, only: [:show]
    end
  end
end

app/models/federails/following.rb
module Federails
  class Following < ApplicationRecord
    enum status: { pending: 0, accepted: 1 }

    validates :target_actor_id, uniqueness: { scope: [:actor_id, :target_actor_id] }

    belongs_to :actor
    belongs_to :target_actor, class_name: 'Federails::Actor'
    # FIXME: Handle this with something like undelete
    has_many :activities, as: :entity, dependent: :destroy

    after_create :create_activity
    after_destroy :destroy_activity

    scope :with_actor, ->(actor) { where(actor_id: actor.id).or(where(target_actor_id: actor.id)) }

    def federated_url
      attributes['federated_url'].presence || Federails::Engine.routes.url_helpers.server_actor_following_url(actor_id: actor_id, id: id)
    end

    def accept!
      update! status: :accepted
      Activity.create! actor: target_actor, action: 'Accept', entity: self
    end

    class << self
      def new_from_account(account, actor:)
        target_actor = Actor.find_or_create_by_account account
        new actor: actor, target_actor: target_actor
      end
    end

    private

    def create_activity
      Activity.create! actor: actor, action: 'Create', entity: self
    end

    def destroy_activity
      Activity.create! actor: actor, action: 'Undo', entity: self
    end
  end
end

app/controllers/federails/client/activities_controller.rb
module Federails
  module Client
    class ActivitiesController < Federails::ApplicationController
      before_action :authenticate_user!, only: [:feed]
      # layout 'layouts/application'

      # GET /app/activities
      # GET /app/activities.json
      def index
        @activities = policy_scope(Federails::Activity, policy_scope_class: Federails::Client::ActivityPolicy::Scope).all
        @activities = @activities.where actor_id: params[:actor_id] if params[:actor_id]
      end

      # GET /app/feed
      # GET /app/feed.json
      def feed
        @activities = Activity.feed_for(current_user.actor)
      end
    end
  end
end

app/controllers/federails/client/actors_controller.rb
module Federails
  module Client
    class ActorsController < Federails::ApplicationController
      before_action :set_actor, only: [:show]

      # GET /app/actors
      # GET /app/actors.json
      def index
        @actors = policy_scope(Federails::Actor, policy_scope_class: Federails::Client::ActorPolicy::Scope).all
      end

      # GET /app/actors/1
      # GET /app/actors/1.json
      def show; end

      # GET /app/explorer/lookup
      # GET /app/explorer/lookup.json
      def lookup
        @actor = Federails::Actor.find_by_account account_param
        authorize @actor, policy_class: Federails::Client::ActorPolicy
        render :show
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_actor
        @actor = Federails::Actor.find(params[:id])
        authorize @actor, policy_class: Federails::Client::ActorPolicy
      end

      def account_param
        params.require('account')
      end
    end
  end
end

app/controllers/federails/client/followings_controller.rb
module Federails
  module Client
    class FollowingsController < Federails::ApplicationController
      before_action :authenticate_user!
      before_action :set_following, only: [:accept, :destroy]

      # PUT /app/followings/:id/accept
      # PUT /app/followings/:id/accept.json
      def accept
        respond_to do |format|
          url = federails.client_actor_url @following.actor
          if @following.accept!
            format.html { redirect_to url, notice: I18n.t('controller.followings.accept.success') }
            format.json { render :show, status: :ok, location: @following }
          else
            format.html { redirect_to url, alert: I18n.t('controller.followings.accept.error') }
            format.json { render json: @following.errors, status: :unprocessable_entity }
          end
        end
      end

      # POST /app/followings
      # POST /app/followings.json
      def create
        @following = Following.new(following_params)
        @following.actor = current_user.actor
        authorize @following, policy_class: Federails::Client::FollowingPolicy

        save_and_render
      end

      # POST /app/followings/follow
      # POST /app/followings/follow.json
      def follow
        begin
          @following = Following.new_from_account following_account_params, actor: current_user.actor
          authorize @following, policy_class: Federails::Client::FollowingPolicy
        rescue ::ActiveRecord::RecordNotFound
          # Renders a 422 instead of a 404
          respond_to do |format|
            format.html { redirect_to federails.client_actors_url, alert: I18n.t('controller.followings.follow.error') }
            format.json { render json: { target_actor: ['does not exist'] }, status: :unprocessable_entity }
          end

          return
        end

        save_and_render
      end

      # DELETE /app/followings/1
      # DELETE /app/followings/1.json
      def destroy
        @following.destroy
        respond_to do |format|
          format.html { redirect_to federails.client_actor_url(@following.actor), notice: I18n.t('controller.followings.destroy.success') }
          format.json { head :no_content }
        end
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_following
        @following = Following.find(params[:id])
        authorize @following, policy_class: Federails::Client::FollowingPolicy
      end

      # Only allow a list of trusted parameters through.
      def following_params
        params.require(:following).permit(:target_actor_id)
      end

      def following_account_params
        params.require(:account)
      end

      def save_and_render # rubocop:disable Metrics/AbcSize
        url = federails.client_actor_url current_user.actor

        respond_to do |format|
          if @following.save
            format.html { redirect_to url, notice: I18n.t('controller.followings.save_and_render.success') }
            format.json { render :show, status: :created, location: @following }
          else
            format.html { redirect_to url, alert: I18n.t('controller.followings.save_and_render.error') }
            format.json { render json: @following.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end
end

app/controllers/federails/server/followings_controller.rb
module Federails
  module Server
    class FollowingsController < ServerController
      before_action :set_following, only: [:show]

      # GET /federation/actors/1/followings/1.json
      def show; end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_following
        @following = Following.find_by!(actor_id: params[:actor_id], id: params[:id])
        authorize @following, policy_class: Federails::Server::FollowingPolicy
      end
    end
  end
end

app/views/federails/client/followings/_follow.html.erb
<div>
  <b><%= link_to following.target_actor.name, federails.client_actor_url(following.target_actor) %></b>
  (<%= following.target_actor.at_address %>) (<%= following.status %>)
</div>

app/views/federails/client/followings/_follower.html.erb
<div>
  <b><%= link_to following.actor.name, federails.client_actor_url(following.actor) %></b>
  (<%= following.actor.at_address %>) (<%= following.status %>)
  <% if following.pending? && following.target_actor == current_user.actor %>
    <%= button_to 'Accept', federails.accept_client_following_path(following), method: :put %>
  <% end %>
</div>

app/views/federails/client/followings/_form.html.erb
<%= form_for following, url: federails.client_following_url do |f| %>
  <% if following.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(following.errors.count, 'error') %> prohibited this following from being saved:</h2>
      <ul>
        <% following.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :target_actor %>
    <%= f.collection_select :target_actor_id, Federails::Actor.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/federails/client/followings/index.html.erb
<h1>Listing followings</h1>

<table>
  <thead>
  <tr>
    <th>Actor</th>
    <th>Target actor</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @followings.each do |following| %>
    <tr>
      <td><%= following.actor %></td>
      <td><%= following.target_actor %></td>
      <td><%= following.status %></td>
      <td><%= link_to 'Show', following %></td>
      <td><%= link_to 'Edit', edit_following_path(following) %></td>
      <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Following', new_following_path %>

app/views/federails/client/followings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Actor:</b>
  <%= @following.actor %>
</p>

<p>
  <b>Target actor:</b>
  <%= @following.target_actor %>
</p>

<p>
  <b>Status:</b>
  <%= @following.status %>
</p>


<%= link_to 'Edit', edit_following_path(@following) %>
\|
<%= link_to 'Back', followings_path %>